version: "3.9"

services:
    pgdatabase:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        expose:
            - 5432
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/:rw
    taskmanager:
        image: tork83/task-manager:latest
#        build:
#            context: ../
#            dockerfile: docker/services/task-manager/Dockerfile
#        working_dir: /app
        environment:
        - DATABASE_URL=postgresql://postgres:postgres@pgdatabase:5432/postgres
        expose:
        - 8000
        depends_on:
        - pgdatabase
    nginx:
        build: ./services/nginx
        ports:
            - 8000:80
        depends_on:
            - taskmanager
volumes:
    pgdata:
