# Generated by Django 4.1.3 on 2022-12-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
        ('tasks', '0005_alter_task_performer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.mark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='mark',
            field=models.ManyToManyField(through='tasks.Bond', to='marks.mark'),
        ),
    ]
