name: test
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
            - name: chekout repo
              uses: actions/checkout@v2
            - name: setup python
              uses: actions/setup-python@v2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
                  pip install -r requirements.txt
            - name: run tests
              run: |
                  make test