# Generated by Django 4.1.3 on 2022-12-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='timestamp',
            new_name='date_joined',
        ),
    ]
