# Generated by Django 4.1.3 on 2022-12-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_rename_timestamp_status_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
